version: 1.62

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - goconst
    - gosec
    - errcheck
    - ineffassign
    - gosimple
    - unused
    - prealloc

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
